// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wirex

import (
	"context"
	"github.com/yz271544/settlement-monitoring/v10/internal/mods"
	"github.com/yz271544/settlement-monitoring/v10/internal/mods/guard"
	api2 "github.com/yz271544/settlement-monitoring/v10/internal/mods/guard/api"
	biz2 "github.com/yz271544/settlement-monitoring/v10/internal/mods/guard/biz"
	dal2 "github.com/yz271544/settlement-monitoring/v10/internal/mods/guard/dal"
	"github.com/yz271544/settlement-monitoring/v10/internal/mods/rbac"
	"github.com/yz271544/settlement-monitoring/v10/internal/mods/rbac/api"
	"github.com/yz271544/settlement-monitoring/v10/internal/mods/rbac/biz"
	"github.com/yz271544/settlement-monitoring/v10/internal/mods/rbac/dal"
	"github.com/yz271544/settlement-monitoring/v10/pkg/util"
)

// Injectors from wire.go:

func BuildInjector(ctx context.Context) (*Injector, func(), error) {
	db, cleanup, err := InitDB(ctx)
	if err != nil {
		return nil, nil, err
	}
	cacher, cleanup2, err := InitCacher(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	auther, cleanup3, err := InitAuth(ctx)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	trans := &util.Trans{
		DB: db,
	}
	menu := &dal.Menu{
		DB: db,
	}
	menuResource := &dal.MenuResource{
		DB: db,
	}
	roleMenu := &dal.RoleMenu{
		DB: db,
	}
	bizMenu := &biz.Menu{
		Cache:           cacher,
		Trans:           trans,
		MenuDAL:         menu,
		MenuResourceDAL: menuResource,
		RoleMenuDAL:     roleMenu,
	}
	apiMenu := &api.Menu{
		MenuBIZ: bizMenu,
	}
	role := &dal.Role{
		DB: db,
	}
	userRole := &dal.UserRole{
		DB: db,
	}
	bizRole := &biz.Role{
		Cache:       cacher,
		Trans:       trans,
		RoleDAL:     role,
		RoleMenuDAL: roleMenu,
		UserRoleDAL: userRole,
	}
	apiRole := &api.Role{
		RoleBIZ: bizRole,
	}
	user := &dal.User{
		DB: db,
	}
	bizUser := &biz.User{
		Cache:       cacher,
		Trans:       trans,
		UserDAL:     user,
		UserRoleDAL: userRole,
	}
	apiUser := &api.User{
		UserBIZ: bizUser,
	}
	login := &biz.Login{
		Cache:       cacher,
		Auth:        auther,
		UserDAL:     user,
		UserRoleDAL: userRole,
		MenuDAL:     menu,
		UserBIZ:     bizUser,
	}
	apiLogin := &api.Login{
		LoginBIZ: login,
	}
	logger := &dal.Logger{
		DB: db,
	}
	bizLogger := &biz.Logger{
		LoggerDAL: logger,
	}
	apiLogger := &api.Logger{
		LoggerBIZ: bizLogger,
	}
	casbinx := &rbac.Casbinx{
		Cache:           cacher,
		MenuDAL:         menu,
		MenuResourceDAL: menuResource,
		RoleDAL:         role,
	}
	rbacRBAC := &rbac.RBAC{
		DB:        db,
		MenuAPI:   apiMenu,
		RoleAPI:   apiRole,
		UserAPI:   apiUser,
		LoginAPI:  apiLogin,
		LoggerAPI: apiLogger,
		Casbinx:   casbinx,
	}
	staff := &dal2.Staff{
		DB: db,
	}
	bizStaff := &biz2.Staff{
		StaffDal: staff,
	}
	apiStaff := &api2.Staff{
		StaffBiz: bizStaff,
	}
	scene := &dal2.Scene{
		DB: db,
	}
	bizScene := &biz2.Scene{
		SceneDal: scene,
	}
	apiScene := &api2.Scene{
		SceneBiz: bizScene,
	}
	plotting := &dal2.Plotting{
		DB: db,
	}
	bizPlotting := &biz2.Plotting{
		PlottingDal: plotting,
	}
	apiPlotting := &api2.Plotting{
		PlottingBiz: bizPlotting,
	}
	guardGuard := &guard.Guard{
		DB:          db,
		StaffAPI:    apiStaff,
		SceneAPI:    apiScene,
		PlottingAPI: apiPlotting,
	}
	modsMods := &mods.Mods{
		RBAC:  rbacRBAC,
		Guard: guardGuard,
	}
	injector := &Injector{
		DB:    db,
		Cache: cacher,
		Auth:  auther,
		M:     modsMods,
	}
	return injector, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
